export const example = {
  "idDrink": "17248",
  "strDrink": "French Negroni",
  "strDrinkAlternate": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Cocktail",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Martini Glass",
  "strInstructions": "Add ice to a shaker and pour in all ingredients.\nUsing a bar spoon, stir 40 to 45 revolutions or until thoroughly chilled.\nStrain into a martini glass or over ice into a rocks glass. Garnish with orange twist.",
  "strInstructionsES": null,
  "strInstructionsDE": "F\u00fcge Eis in einen Shaker und gie\u00dfe alle Zutaten ein. R\u00fchren Sie mit einem Barl\u00f6ffel 40 bis 45 Umdrehungen oder bis zur vollst\u00e4ndigen Abk\u00fchlung. In ein Martini-Glas oder \u00fcber Eis in ein Rocks Glas abseihen. Mit Orangenspirale garnieren.",
  "strInstructionsFR": null,
  "strInstructionsIT": "Versare tutti gli ingredienti in uno shaker con cubetti di ghiaccio.\r\nShakerare bene e filtrare in una coppetta da cocktail fredda.\r\nSpremi l'olio dalla scorza di limone sulla bevanda.",
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/x8lhp41513703167.jpg",
  "strIngredient1": "Gin",
  "strIngredient2": "Lillet",
  "strIngredient3": "Sweet Vermouth",
  "strIngredient4": "Orange Peel",
  "strIngredient5": null,
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "1 oz",
  "strMeasure2": "1 oz",
  "strMeasure3": "1 oz",
  "strMeasure4": "1",
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strImageSource": null,
  "strImageAttribution": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2017-12-19 17:06:07"
}
